### ISSUE TITLE
Next/Previous on Swipe gesture

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#19]
When clicking on a torrent, it might be a good idea to have a swipe gesture to go the next/previous torrent in the  previous torrent list.

If I do a search it should move between the torrents in the result list. If I didn't do a search it should move between the last torrents. If I clicked on a recent viewed torrent, it should move between the last viewed torrent list.

**Comment by ltype** [comment]
Good idea, I can do this.

**Comment by xdk78** [comment]
Resolved by #20
