### ISSUE TITLE
Fix minor code issues

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#23]
- [x] adapters to separate packages (resolved by #21) 
- ~~better data transfer between activities, fragments.. more code to other classes~~ moved to v1.3
- [x] fix after click on stream button and back to other fragment than torrent app crashing after few seconds

**Comment by akuma06** [comment]
Will try to replicate the bug and see what is causing it

**Comment by akuma06** [comment]
I still don't seem to be able to replicate the bug, do you have an error message?

**Comment by xdk78** [comment]
~~`better data transfer between activities, fragments.. more code to other classes`
Ok I will start do this~~

**Comment by xdk78** [comment]
~~https://github.com/greenrobot/EventBus for ` communication between Activities, Fragments, Threads, Services, etc` or something like this
This looks cool too https://github.com/lsxiao/Apollo/blob/master/README-EN.md~~
We don't need this right now

**Comment by akuma06** [comment]
@xdk78 Does it mean we can close this issue for 1.2 or you still have things you want to add?

**Comment by xdk78** [comment]
I think is good for now
