### ISSUE TITLE
RecyclerView Adapter instead BaseAdapter

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#24]
For better performance and customisation

**Comment by xdk78** [comment]
W.I.P https://github.com/NyaaPantsu/NyaaPantsu-android-app/commit/71944d829dc21f866274aba61b5c30e676695385
I have only (probably) one issue and i need help
`holder?.itemView?.setOnClickListener { i ->
context.startActivity<TorrentActivity>("position" to i, "type" to "search")
}`

**Comment by akuma06** [comment]
Should be fixed now.

**Comment by xdk78** [comment]
Thx

**Comment by xdk78** [comment]
resolved by https://github.com/NyaaPantsu/NyaaPantsu-android-app/commit/71944d829dc21f866274aba61b5c30e676695385 and https://github.com/NyaaPantsu/NyaaPantsu-android-app/commit/28d845d7d4515fd1b21ca2231c9a58544bf99f29
