### ISSUE TITLE
Make settings working

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#27]
Settings "frontend" it's just finished, so we need to make working saving ~~user login~~, etc to shared prefs

**Comment by akuma06** [comment]
I don't understand what you meant :/. What is not working?

**Comment by xdk78** [comment]
Data and sync

**Comment by ltype** [comment]
Data&Sync seems just make search result auto reload, user can do that with swipe, maybe we can remove it?

**Comment by xdk78** [comment]
@ltype ok
