### ISSUE TITLE
Using TorrentStream direclty makes player unable to read the video files while downloading

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#29]
As said above (and previously in another commit in 1.1), TorrentStram makes it impossible to read a file while downloading a torrent. Since TorrentStream only provides the ability to download a file, not the ability to "Stream" it to the player. So the player stops playing and close itself.

**Comment by akuma06** [comment]
@ltype Is it possible to use TorrentStreamServer instead of TorrentStream in TorrentStreamHelper?

**Comment by ltype** [comment]
Okay, I will fix it.
Should we add a only download option on stream button, or just watch a video?

**Comment by akuma06** [comment]
I don't know but might be a good idea. What do you think @xdk78 ?

**Comment by xdk78** [comment]
2 buttons are OK, download and stream

**Comment by xdk78** [comment]
*download by the torrent library

**Comment by ltype** [comment]
Mmm, I try play video with TorrentStream(MXPlayer), It seems all is going well.

**Comment by xdk78** [comment]
I also tested using Mx player

**Comment by akuma06** [comment]
I'm using default player from galaxy s8 and VLC. Both gives read error while playing the stream, as long as it is not done downloading. Also tried with MX Player and doesn't work, it gives the error: "can't play the file".

**Comment by ltype** [comment]
Mmm
I used TorrentStreamHelper.instance.stop() in onStreamReady(), that will be throw a error.
#https://github.com/ltype/NyaaPantsu-android-app/commit/b644fd2e69794659d1ac24915b932fd7bfaa8672 now should be work fine
@akuma06 @xdk78

**Comment by xdk78** [comment]
@akuma06 have you still issues with this?

**Comment by akuma06** [comment]
Yeah it's fixed =)
