### ISSUE TITLE
Ability to select multiple languages 

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#31]
Now we can select only one language. We should move to the new design of nyaapantsu and provide the ability to select multiple languages.
I'm thinking of adding a system like "tags" instead of the actual select

**Comment by xdk78** [comment]
Like this https://github.com/whilu/AndroidTagView ?

**Comment by akuma06** [comment]
Yes something like this :)

**Comment by akuma06** [comment]
I'm thinking of using this, what are your thoughts? https://github.com/pchmn/MaterialChipsInput?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=5584

**Comment by xdk78** [comment]
Yes, looks better
