### ISSUE TITLE
Add magnet upload in the upload form

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#32]

**Comment by ltype** [comment]
I want redesign upload form with Material Design.

**Comment by ltype** [comment]
Like [this](https://imgur.com/a/V2f6p)

**Comment by xdk78** [comment]
Ok

**Comment by xdk78** [comment]
Please push to user profile branch, because I did some changes like renamed layouts.

**Comment by akuma06** [comment]
@xdk78 maybe just push to master?

**Comment by ltype** [comment]
I only modify fragment_upload.xml and UploadFragment.kt, seems no conflict happens.

**Comment by ltype** [comment]
I am trying to add a spinner to switch upload type(file/magnet)
