### ISSUE TITLE
Possibility to interact with cardview by swipe left

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#34]
For example displaying a magnet button and download button and a possible stream button.

**Comment by xdk78** [comment]
Like Gmail Swipe to delete item?

**Comment by akuma06** [comment]
I'm using default player from galaxy s8 and VLC. Both gives read error while playing the stream, as long as it is not done downloading. Also tried with MX Player and doesn't work, it gives the error: "can't play the file".

**Comment by akuma06** [comment]
However Torrent Stream Server doesn't give error since it streams the file through a nanohttpd server.

**Comment by ltype** [comment]
Swipe to delete item on RecentFragment?

**Comment by xdk78** [comment]
And torrent list too, after swipe show download and stream button. I think good?

**Comment by ltype** [comment]
Not suggest add button while swipe with cardview.
Add a extend button maybe a good way to do this.

**Comment by ltype** [comment]
Please see [Leave-behinds](https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls) and [Cards](https://material.io/guidelines/components/cards.html#cards-usage).

**Comment by xdk78** [comment]
Ok you right

**Comment by akuma06** [comment]
So might be best to add two simple button (link) at the bottom of each cardview then? Download and Stream? Or Magnet?

**Comment by ltype** [comment]
What do you think about this design?

**Comment by xdk78** [comment]
@ltype it's ok but this is better imo http://imgur.com/a/tlk7b
sorry for paint 😄

**Comment by xdk78** [comment]
instead expand just 2 bottom buttons

**Comment by ltype** [comment]
I tried this. but have some problem.
I'd like to show more item in one screen. That make user fast view all item.

**Comment by akuma06** [comment]
Another way, maybe a long press on a card reveal the two buttons?

**Comment by xdk78** [comment]
Long press and show pop up menu?

**Comment by xdk78** [comment]
Overall I stay on idea to add buttons like I said before

**Comment by ltype** [comment]
In [Material Design](https://material.io/), not recommend use long press on a card.

**Comment by xdk78** [comment]
Guys http://www.strawpoll.me/13450355 xdddd

**Comment by akuma06** [comment]
Seems like collapsing like @ltype did is the way to go :')

**Comment by akuma06** [comment]
Seems to be done
