### ISSUE TITLE
Add user profile like on website

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#36]
Profile with your torrents, notifications and profile settings.
We need to talk about this activity/fragment design and other shit 😄

**Comment by xdk78** [comment]
I'm started writing user profile layout

**Comment by xdk78** [comment]
preview: http://imgur.com/RxOjTID
and https://github.com/NyaaPantsu/NyaaPantsu-android-app/commit/e1ce60be62c08b51d6e04d4a35cf9c36a01f4941

**Comment by akuma06** [comment]
Oh I like the design =D.

**Comment by xdk78** [comment]
of course instead many textview with "ur torrent" we will use recyclerview to display this from api etc

**Comment by akuma06** [comment]
Yeah I got it. Just need to reuse what we have :')

**Comment by xdk78** [comment]
I added Placeholder data from recent, what do you think? http://imgur.com/o0HGEG3
http://imgur.com/Mg3tGA6

**Comment by xdk78** [comment]
btw where i find endpoints for api?

**Comment by akuma06** [comment]
Yeah I like it =).
For the api, you have: https://dev.pantsu.cat/apidoc/

**Comment by xdk78** [comment]
I have problem User.id always return 0. I want to use this ID to get user torrents. It would be a great idea to add more 
endpoints to Nyaa api like /user/torrents which return all user torrents instead using /search/

**Comment by akuma06** [comment]
@xdk78 https://nyaa.pantsu.cat/api/search?userID=xx <= should return all user torrents

**Comment by xdk78** [comment]
Ok, I fixed user ID https://github.com/NyaaPantsu/NyaaPantsu-android-app/commit/4d715d93fd42881d1d66e770a7d9c7f9ed0e4872
