### ISSUE TITLE
Possibility to watch anime from torrent inside app

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#5]
What do u think about this?
I would like to use https://github.com/TorrentStream/TorrentStream-Android library or something like that  to download/watch videos and other shit from torrrent inside app 😄 😄 😄 😄

**Comment by akuma06** [comment]
Yeah seems quite good actually (and easy to implement).
The workflow would be to have a fragment "downloads"  listing the downlads/options to delete/stop a torrent. And when you want to add a download, you just start the fragment with the torrent url?

That might be a great improvement on the app :D

**Comment by xdk78** [comment]
> you just start the fragment with the torrent url?

This seems good: https://github.com/TorrentStream/TorrentStream-Android/blob/develop/sample/src/main/java/com/github/se_bastiaan/torrentstreamer/sample/MainActivity.java
For now just like that
`Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(torrent.getVideoFile().toString()));
        intent.setDataAndType(Uri.parse(torrent.getVideoFile().toString()), "video/mp4");
        startActivity(intent);`
or write video player for this

**Comment by akuma06** [comment]
Sorry I didn't get the real intent of the library. It's a torrent player? Cool, then you don't actually have to do the torrent workflow =D. Just need to start the library intent :)

However, might be interesting to add a fragment with the "recently payed stuff" or a "Playlist", so you don't have to do the search everytime.

To have the torrentlist, you would only need to copy how to create a torrent list object : KotprefModel() with some torrents property (json array?).  And then we only add a torrent to the list at the same time we start the intent?

**Comment by xdk78** [comment]
> It's a torrent player?

yes 😅 sorry for misunderstood 

> However, might be interesting to add a fragment with the "recently payed stuff" or a "Playlist", so you don't have to do the search everytime

good idea

**Comment by xdk78** [comment]
Just add magnet or .torrent and `torrent.getVideoFile().toString()), "video/mp4"`
that's it!

**Comment by xdk78** [comment]
In free time I want start write and test basic stuff for app.

**Comment by akuma06** [comment]
Yeah you can :). I can't help you for now (I'm on the refactoring of NyaaPantsu main website) but if you need help, ask here or on IRC =)

**Comment by xdk78** [comment]
So, I just little improved app code and almost finished writing basic video streaming from .torrent

**Comment by akuma06** [comment]
Oh neat! :D For my part I'm stuck on CSRF validation in refactoring :')

**Comment by akuma06** [comment]
I've gone through your code. It's really good! Sorry for not having done activities/fragments separation and all, it was done a bit in a hurry :p. 
I just have a question so far, why do you think it is better to have a minSdk to 21? I think 19 might be better since we would target kitkat as well. (https://developer.android.com/about/dashboards/index.html)

**Comment by xdk78** [comment]
app using material design(i know, it's compatible with 19) so I think it's time to use super new tech features from sdk 21+ without preparing for old phones.
btw STREAMING WORKING!!! 😄 
now im adding ProgressDialog 😄 to show progress buffering, when stream is ready.

**Comment by xdk78** [comment]
Some screen shots 

http://imgur.com/rrp36Ty

http://imgur.com/2bOyx8v
 and after that opening Intent chooser, u can choose video plaayer for example mx player

**Comment by akuma06** [comment]
Great =D. This might come the most used app on my phone now =D

**Comment by xdk78** [comment]
Thx. Now it's time to upgrade this shit code. It would be nice if you help me :)

**Comment by akuma06** [comment]
I will, don't worry :). Just need to finish my own work before ^^

**Comment by xdk78** [comment]
Btw I want to assign myself to more issues, could u add me to contributors with access to this repo?

**Comment by xdk78** [comment]
I'm rewriting adapters from BaseAdapter to RecyclerView for better control and more features 

edit:
I have some issues(im not good to convert my java skills to kotlin 😄 ) https://github.com/xdk78/NyaaPantsu-android-app/commit/076c6e68070ac9661f3e4978176698ac6e437d2e
If u have moment pls look

**Comment by akuma06** [comment]
@xdk78 Didn't see your comments on this issue. For the contributor access, I have to ask @ewhal for that, I can't take a decision :).
Will take a look to recycler view conversion :)

**Comment by akuma06** [comment]
We should close this issue (since we now have anime streaming) and keep things ordered. If you need some help, open a new issue, that would be better I think =)
