### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by synthetichuman** [NyaaPantsu/NyaaPantsu-android-app#67]
I can't even get it to open, just crashes every time

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xdk78** [comment]
More info please:
- Android version 
- App version 
- Logs from Logcat(if you have)

**Comment by xdk78** [comment]
I don't have any problems, tested on Android 6.0

**Comment by synthetichuman** [comment]
I don't know how to do logcat

But I'm running android 7.1.2
And 1.0 of the app

It crashes after clicking megumin and then crashes over and over.

**Comment by xdk78** [comment]
Download newest version of the app 1.2, see Releases https://github.com/NyaaPantsu/NyaaPantsu-android-app/releases/tag/v1.2

**Comment by akuma06** [comment]
Hi @synthetichuman! Great that you use our app!
As @xdk78 mentionned earlier, the 1.0 app is a bit outdated and we have fixed/refactored so many things between 1.0 and 1.2.
If you are on 1.0, it seems you might have donwloaded it through Fdroid. If that's the case, you should either wait for them to update the app to the new version or download the signed apk from here (or our through the aptoid store).

We would be grateful if you have the time to test the 1.2 version and give us a feedback about your crash.

Thank you in advance 😄

**Comment by synthetichuman** [comment]
Actually I've never used it before, and you guessed right, it was f-droid I
downloaded from. I just snagged the latest apk off github and it stated
right up.

**Comment by akuma06** [comment]
Ok thanks for the feedback. I will try to ask fdroid, if there are anyway to speed up version deployments.
