### ISSUE TITLE
Migrate from Fuel to Retrofit

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#69]

**Comment by xdk78** [comment]
@akuma06 Which parameter is deprecated https://nyaa.pantsu.cat/apidoc/#api-Torrents-FindTorrents  ?

**Comment by akuma06** [comment]
None however you will have this soon https://github.com/NyaaPantsu/nyaa/issues/1334

**Comment by xdk78** [comment]
After few hours rewriting the code, I got a cancer.
There are too much breaking code changes to do this. Might be in  v2.0 I will start do this again.
😄

**Comment by xdk78** [comment]
#22
