### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by JuanjoSalvador** [NyaaPantsu/NyaaPantsu-android-app#70]
I was working on the Spanish translation of NyaaPantsu App. My translation is at 82% now, it need to be re-checked and fix minor issues context-related.

I think I can have a full translate in few days.

**Comment by akuma06** [comment]
Just do a PR when you think you have finished/you have some issues. And we will help you then =).

**Comment by JuanjoSalvador** [comment]
Few days ago, I sent the Spanish translation of NyaaPantsu, so... :yum: 

This translation is a bit special, and easier than the other one, but I need to check few things first. I'm glad to help!

**Comment by JuanjoSalvador** [comment]
Update: translation at 95% with context fixes.
