### ISSUE TITLE
Travis test returns an error, should it be fixed?

### ISSUE THREAD

**Issue by JuanjoSalvador** [NyaaPantsu/NyaaPantsu-android-app#72]
I'm not sure if you are using travis tests for local testing or just for the badge (both, I guess!) but the second one returns an error by trying to create an android emulator, should it be removed in purpose to fix the badge/travis tests?

I have a lot to learn about TDD, so sorry for the possibly absurd questions.

**Comment by xdk78** [comment]
Travis have cancer and sometimes when everything is good he gives us error 😃

**Comment by JuanjoSalvador** [comment]
OK, it's good to know xD Closing the issue then.
