### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by JuanjoSalvador** [NyaaPantsu/NyaaPantsu-android-app#73]
Trying to build the app inside `dev` branch running:

    ./gradlew clean build

I get this error.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

Any ideas?

**Comment by akuma06** [comment]
Hum... Will look at it tomorrow but try this in the main time: https://stackoverflow.com/questions/46053902/dex-error-on-android-studio-3-0-beta4

**Comment by JuanjoSalvador** [comment]
I'm not using Android Studio, but I will check that. Thanks @akuma06!

**Comment by JuanjoSalvador** [comment]
OK, fixed! [This solution](https://stackoverflow.com/a/47023992/4210110) works for me.

I added `multiDexEnabled true` to app/build.gradle and now it works!

**Comment by xdk78** [comment]
Dev is unstable

**Comment by JuanjoSalvador** [comment]
I supossed that. But I'm getting the same build error on `master`. The linked fixing works for both.

**Comment by xdk78** [comment]
Have you newest Android Studio version (3.0)? Are you tried Clean Build and Rebuild?

**Comment by JuanjoSalvador** [comment]
I upgraded Gradle and it works again. But the app (master) is a bit unstable on Android emulator.
